README.md

fixed central link

---

README.md

Provide links to client implementations in readme

---

cd/before-deploy.sh

fixed wrong file path for key

---

.travis.yml
cd/deploy.sh

try without signing

---

pom.xml

tested that Eclipse Client tests are still passing too

#52 - upgrade lsp4j from 0.3.0 to 0.3.1

---

src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelTextDocumentServiceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionBooleanValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionEnumerationValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelLanguageServerCompletionPositionTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java

#50 - rename test package name from org.apache to com.github

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/FilterPredicateUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamKeyURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamValueURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointOptionDuplicateTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointUriCompletionTest.java

added filter for already defined endpoint options (#28)

---

src/main/java/com/github/cameltooling/lsp/internal/completion/FilterPredicateUtils.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/resources/workspace/cbr-blueprint.xml

fixed javadocs and added test and logic for initialize language server from file

---

pom.xml

#62 - Upgrade Camel from 2.21.0 to 2.21.1

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java

#67 - Provide documentation for attributes on completion

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java

result in combination with https://github.com/camel-tooling/camel-language-server/pull/70

#71 - provide Java type as Detail for Camel URI attributes

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java

#77 - remove unused hardcoded Camel version

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java

#77 - remove useless curly brace

---

.travis.yml
cd/deploy.sh
pom.xml

fix scripts to enable clean releases

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java

- debug adapter protocol ready
- several fixes

#95 - upgrade lsp4j from 0.3.0 to 0.4.1

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/hover/HoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/DSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/JavaDSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/XMLDSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserJavaFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelTextDocumentServiceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointUriCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java
src/test/resources/workspace/camel.java

I recommend to review https://github.com/camel-tooling/camel-language-server/pull/97 first
please note that clients needs to be updated to have a visible effect to users (PR coming)

93 support position finding of camel u ri in java file

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserJavaFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java

see https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AWRbo7ti1IJZDfsS41kr&open=AWRbo7ti1IJZDfsS41kr

Avoid throwing generic exception

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java

Remove exception declaration which cannot be thrown anymore

---

src/main/java/com/github/cameltooling/lsp/internal/completion/FilterPredicateUtils.java

Write ternary with if-else to improve readability

---

src/main/java/com/github/cameltooling/lsp/internal/AbstractLanguageServer.java

Re-interrupt thread when catching InterruptedException

---

pom.xml

upgrades also camel-common-tooling using Camel 2.22.0

Upgrade to Camel 2.22.0 (#105)

---

pom.xml

Prepare next iteration development 1.1.0-SNAPSHOT

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/AbstractLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelEndpointDetailsWrapper.java
src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-endpoint-2-errors.xml
src/test/resources/workspace/diagnostic/camel-with-endpoint-boolean-error.xml
src/test/resources/workspace/diagnostic/camel-with-endpoint-error.xml
src/test/resources/workspace/diagnostic/camel-with-endpoint-integer-error.xml
src/test/resources/workspace/diagnostic/camel-with-endpoint.xml
src/test/resources/workspace/diagnostic/camel.java

requires https://github.com/camel-tooling/camel-tooling-common/pull/26 to be reviewed and merged

Provide diagnostic for endpoints for XML DSL on save (#30)

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-endpoint-error.java

Support Diagnostic of Camel URI for java dsl (#110)

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentSchemesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelDeprecationIndicatorInCompletionTest.java

parameters (#195)
please note that Clients are nto supporting it yet, so nothing is
changing in UI yet...

Support deprecated information on Camel component and Component

---

.classpath
.settings/org.eclipse.jdt.core.prefs

due to separation of main and test classpath

Fix project metadata to work with Eclipse Photon

---

.classpath
.settings/org.eclipse.jdt.core.prefs
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java

81 include camel context in document symbol

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessorTest.java

Support references for direct/direct-vm in XML dsl (#132)

---

src/main/java/com/github/cameltooling/lsp/internal/hover/HoverFuture.java
src/main/java/com/github/cameltooling/lsp/internal/hover/HoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamKeyURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamValueURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java

display hover doc for the element under the cursor #69

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointUriCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelperTest.java
src/test/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessorTest.java
src/test/resources/workspace/diagnostic/camel-with-endpoint-error-withNamespacePrefix.xml

Support prefix for Camel namespace uri with xml dsl

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CompletionResolverUtils.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserJavaFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionEnumerationValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelLanguageServerCompletionPositionTest.java

- fix default values on completion regression
- fix completion with empty uri

Fix regression for default values completion (#150)

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessorTest.java

Fix find references when there is an empty URI in the file (#155)

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentSchemesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CompletionResolverUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ModelUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamKeyURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamValueURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CompleteIdOnDirectEndpointsTest.java
src/test/resources/workspace/direct-endpoint-test.xml

added completions for existing direct, direct-vm, vm and seda endpoints #158

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentSchemesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CompletionResolverUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ReferenceUtils.java
src/main/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessor.java

Improve separation of concerns

---

src/main/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessor.java

remove unused import

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java

Upgrade to LSP4J 0.5.0 #168

---

pom.xml

Upgrade SpringBoot from 1.4 to 2.1 (#152)

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelperTest.java
src/test/resources/workspace/camel.java

review https://github.com/camel-tooling/camel-language-server/pull/178 first

177 avoid saxparse exception

---

pom.xml

Upgrade Assertj from 3.10.0 to 3.11.1 #170

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java

Remove unused field and rename variable to be more specific #180

---

pom.xml

added compiler argument -Werror #188

---

pom.xml

Camel version bump to 2.22.2 #185

---

.settings/org.eclipse.jdt.apt.core.prefs
pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ReferenceUtils.java
src/main/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/references/MultiDocumentReferencesProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessorTest.java

make references search multiple documents #135

---

pom.xml

better to review and merge https://github.com/camel-tooling/camel-tooling-common/pull/37 before

Upgrade to Camel 2.23.0 #147

---

pom.xml

Upgrade to LSP4J 0.6.0 #198

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Signed-off-by: Dominik Jelinek <djelinek@redhat.com>

Provide GitHub templates for new issues and PRs #197

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java

Use secure XMl processing #208

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java

Ensure diagnostic is accurate when closing editor without saving #204

---

pom.xml

Upgrade to Camel 2.23.1 #210

---

pom.xml

Upgrade awaitility to 3.1.6 #212

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/definition/DefinitionProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/DummyConstants.java
src/test/java/com/github/cameltooling/lsp/internal/definition/DefinitionProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelperTest.java

Upgrade to LSP4J 0.7.0 #216

---

.travis.yml

Add JDK 12 to CI job matrix #218

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-endpoint-error-withampersand.xml

now message is displayed and range is provided:
4. Approved PR

Support Syntax error #225

---

pom.xml

first release with official Java 11 support and experimental support for
Java 13
4. Approved PR

Upgrade jacoco to 0.8.3 #229

---

pom.xml

Upgrade Camel from 2.23.1 to 2.23.2 #231

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java

see https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AWoRuaOr9zLXaOU8wouP&open=AWoRuaOr9zLXaOU8wouP
4. Approved PR

Remove unused method parameter #225

---

pom.xml

Upgrade to Camel 2.24.0 #235

---

pom.xml

Upgrade LSP4J from 0.7.0 to 0.7.1 #236

---

.travis.yml

Use OpenJDK instead of OracleJDK as Travis changed the supported JDK by

---

pom.xml

Upgrade from Camel 2.24.0 to 2.24.1 #242

---

pom.xml

Upgrade LSP4J from 0.7.1 to 0.7.2 #240

---

pom.xml
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerRobustnesstest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelTextDocumentServiceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionInsertAndReplaceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionBooleanValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionEnumerationValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelDeprecationIndicatorInCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointOptionDuplicateTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointUriCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelLanguageServerCompletionPositionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CompleteIdOnDirectEndpointsTest.java
src/test/java/com/github/cameltooling/lsp/internal/definition/DefinitionProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelperTest.java
src/test/java/com/github/cameltooling/lsp/internal/references/MultiDocumentReferencesProcessorTest.java
src/test/java/com/github/cameltooling/lsp/internal/references/ReferencesProcessorTest.java

- packages org.junit moved to org.junit.jupiter.*
- @Ignore replaced by @Disabled
- Parameterized test using new annotations now @ParameterizedTest
4. Approved PR

Upgrade to Junit 5 #249

---

.travis.yml

Fix JDK used for deploy stage on Travis #251

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PropertiesDSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaConnectDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaConnectDSLParserTest.java
src/test/resources/workspace/camelKafkaconnectSink.properties
src/test/resources/workspace/camelKafkaconnectSource.properties

current limitation:
- properties file needs to be written with '=' without spaces
- reusing classic Camel catalog
4. Approved PR

Support Camel Kafka Connect #254

---

src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKKotlinDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/resources/workspace/sample.camelk.kts
src/test/resources/workspace/sampleWithModelineLike.kts

Support Camel-K Kotlin files #255

---

README.md

Update list of clients #258

---

src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKJSDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/resources/workspace/sample.camelk.js
src/test/resources/workspace/sampleWithModelineLike.js

Support Camel-K JS files #261

---

src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java

Update Api used for AssertJ to avoid deprecated method

---

src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java

Add missing @Test for Kotlin #293

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/YamlDSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKYamlDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/resources/workspace/samplewithModelineLike.yaml
src/test/resources/workspace/samplewithModelineLikeAndShortCut.yaml
src/test/resources/workspace/samplewithModelineLikeUsingFrom.yaml
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInPlainInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInPlainInsideURIUsingMoreSpaces.yaml
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInSingleQuotesInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithEmtpyAttributes.yaml
src/test/resources/workspace/samplewithModelineLikeWithEmtpyAttributesAndSingleQuotes.yaml
src/test/resources/workspace/samplewithModelineLikeWithEmtpyAttributesWithoutQuotes.yaml
src/test/resources/workspace/samplewithModelineLikeWithSingleQuotesInPlainInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithSingleQuotesInSingleQuotesInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithSingleQuotesInsideURI.yaml

adding yaml file support #284

---

.travis.yml

Configure Travis to play test on Java 13 #297

---

.travis.yml
pom.xml

310 fix jacoco sonar issue

---

pom.xml

new SonarCloud version doesn't support anymore the binary jacoco format.
The report xml needs to be generated.
see https://jira.sonarsource.com/projects/MMF/issues/MMF-1651
currently loosing the coverage report but at least avoid failing the
build and unlock development on the branch (at the cost of no more
visibility on test coverage)
4. Approved PR

Avoid build failure with Sonar #310

---

pom.xml

it is still failing on CI even if passing locally. So removing
completely jacoco so that we can unblock master
4. Approved PR

Removing completely Jacoco #310

---

README.md
src/main/java/com/github/cameltooling/lsp/internal/Runner.java
src/main/java/com/github/cameltooling/lsp/internal/websocket/WebSocketRunner.java
src/test/java/com/github/cameltooling/lsp/internal/RunnerWebSocketTest.java

allows to configure hostname, port and contextpath
4. Approved PR

Provide configurable WebSocket parameters #303

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-properties.java

Avoid empty validation error for Camel URi starting with a property #317

---

README.md
pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/CamelWorkspaceService.java
src/main/java/com/github/cameltooling/lsp/internal/settings/JSONUtility.java
src/main/java/com/github/cameltooling/lsp/internal/settings/SettingsManager.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogVersionTest.java

FUSETOOLS2-54 - support using different Camel Catalog version

---

pom.xml

313 restore code coverage

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/RangeChecker.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java

algorithm is not optimal but not detected slowness on basic cases. It is
async anyway.
4. Approved PR

FUSETOOLS2-66 - provide quickfix for unknown properties

---

README.md
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/settings/SettingsManager.java
src/test/java/com/github/cameltooling/lsp/internal/CamelExtraComponentTest.java

provided as a JSON list following the Camel Catalog syntax.
4. Approved PR

FUSETOOLS2-72 - support additional components

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-endpoint-error-on-second-parameter.xml

several parameters
4. Approved PR

FUSETOOLS2-68 - have range restricted to Camel URI when Camel URI have

---

pom.xml
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionInsertAndReplaceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionEnumerationValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelDeprecationIndicatorInCompletionTest.java
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInPlainInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInPlainInsideURIUsingMoreSpaces.yaml
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInSingleQuotesInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithDoubleQuotesInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithSingleQuotesInPlainInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithSingleQuotesInSingleQuotesInsideURI.yaml
src/test/resources/workspace/samplewithModelineLikeWithSingleQuotesInsideURI.yaml

Fusetools2 77 camel3

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaConnectDSLParser.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionNameCompletionTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/337
4. Approved PR

Fusetools2 82 properties components with parameters completion

---

src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/resources/workspace/knative.yaml

FUSETOOLS2-138 - add automated test for Knative CRD yaml files

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionValuesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileValueInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionEnumerationValuesCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstanceTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/339
4. Approved PR

Fusetools2 134 completion enum

---

LICENSE
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentIdsCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PropertiesDSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKGroovyDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKJSDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKKotlinDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKYamlDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaConnectDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperUtil.java
src/main/java/com/github/cameltooling/lsp/internal/websocket/CamelLSPWebSocketEndpoint.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesTopLevelCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/CamelKYamlDSLParserTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaConnectDSLParserTest.java

Use https instead of http to point to Apache license #233

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileValueInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionNameCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstanceTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/340
4. Approved PR

Fusetools2 135 default values

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionValuesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionBooleanValuesCompletionTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/340
4. Approved PR

Fusetools2 136 completion boolean

---

src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogVersionTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelExtraComponentTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelDeprecationIndicatorInCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionBooleanValuesCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionEnumerationValuesCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionNameCompletionTest.java

Factorization of test code

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentIdsCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionValuesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileValueInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionBooleanValuesCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionEnumerationValuesCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionNameCompletionTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/346
4. Approved PR

Fusetools2 137 filtered list

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentIdsCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionValuesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CompletionResolverUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ILineRangeDefineable.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentNamePropertyFileInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentParameterPropertyFileInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileValueInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionBooleanValuesCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionEnumerationValuesCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionNameCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstanceTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/347
4. Approved PR

Fusetools2 179 insert and replace

---

src/main/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfix.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfixTest.java

FUSETOOLS2-185 - avoid stacks when invalid range are provided with

---

README.md

FUSETOOLS2-178 - add information how to use productized catalog

---

src/main/java/com/github/cameltooling/lsp/internal/Runner.java
src/test/java/com/github/cameltooling/lsp/internal/RunnerHelpTest.java

it can be useful for external contributor trying to integrate teh Camel
Language Server in another IDE
4. Approved PR

Provide help on command-line #308

---

src/main/java/com/github/cameltooling/lsp/internal/Runner.java
src/main/java/com/github/cameltooling/lsp/internal/websocket/WebSocketRunner.java
src/test/java/com/github/cameltooling/lsp/internal/RunnerWebSocketTest.java

previously, in fact the loackandlatch with a timeout of 1 second was
like a Thread.sleep as it always went to timeout.
4. Approved PR

Improve Websocket test #307

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionEnumerationValuesCompletionTest.java

FUSETOOLS2-194 - avoid NPE on invalid property key

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/AbstractQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/InvalidEnumQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/InvalidEnumQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-invalid-enum.xml

FUSETOOLS2-70 - provide quickfix for enum values

---

src/main/java/com/github/cameltooling/lsp/internal/codeactions/AbstractQuickfix.java

as recommended by SOnar https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AW-kAlSClHvLoRYISwHC&open=AW-kAlSClHvLoRYISwHC
4. Approved PR

Change body block to expression

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionValuesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionValuesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionInsertAndReplaceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java

- requires update in common
- updated versions of dependencies that are co-related (roaster)
- requires update due to more typed version provided: List of String for
enums
- several properties went from
producer only to common fro ahc-wss
- one text updated due to description having a space added
requires https://github.com/camel-tooling/camel-tooling-common/pull/64
4. Approved PR

FUSETOOLS2-191 - Upgrade from Camel 3.0.1 to Camel 3.1.0

---

src/main/java/com/github/cameltooling/lsp/internal/hover/HoverFuture.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java

FUSETOOLS2-252 - avoid NPE on hover for unknown component names

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/AbstractQuickfix.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java

- update parameters type
- update Quickfix code as Diagnostic.getCode() return type changed from
String to Either<String,Number>
4. Approved PR

FUSETOOLS2-253 - upgrade LSP4J from 0.8.1 to 0.9.0

---

src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java

FUSETOOLS2-253 - fix compilation failure due to colliding merge

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java

as advised by Sonar
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXDJ052TvjqUPhCxeFib&open=AXDJ052TvjqUPhCxeFib
4. Approved PR

Disable access to external entities in XML parsing

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/ConfigurationPropertiesDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/EndpointDiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/AbstractDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelPropertiesDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-valid.properties
src/test/resources/workspace/diagnostic/camel-with-2-errors.properties
src/test/resources/workspace/diagnostic/camel-with-boolean-error.properties
src/test/resources/workspace/diagnostic/camel-with-integer-error.properties
src/test/resources/workspace/diagnostic/camel-with-invalid-enum.properties
src/test/resources/workspace/diagnostic/camel-with-unknownParameter.properties

requires https://github.com/camel-tooling/camel-tooling-common/pull/73

Fusetools2 184 properties diagnostic

---

.travis.yml

remove jdk 12 which is neither a LTS, neither the latest release
4. Approved PR

Add JDK 14 in test matrix

---

pom.xml

FUSETOOLS2-347 - Upgrade to Camel 3.2

---

pom.xml
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogVersionTest.java

required to adjust tests as a component documentation which is used has
been modified
4. Approved PR

FUSETOOLS2-466 - upgrade to Camel 3.3

---

src/test/java/com/github/cameltooling/lsp/internal/RunnerWebSocketTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionInsertAndReplaceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointOptionDuplicateTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstanceTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTest.java
src/test/java/com/github/cameltooling/lsp/internal/references/MultiDocumentReferencesProcessorTest.java

for better readability as reported by Sonar
4. Approved PR

Use isEmpty, isZero, isNull and isPositive

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKTraitManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitProperty.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/GenericCamelKModelineOptionValue.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/ICamelKModelineOptionValue.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitPropertyNameTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOptionTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/396

Fusetools2 519 provide completion for trait property name modeline

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java

Extract constant for Trait

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineOptionNamesHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java

FUSETOOLS2-521 - provide decription on hover for Camel K modeline option

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKTraitManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/ICamelKModelineOptionValue.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineTraitHoverTest.java

FUSETOOLS2-522 - provide hover for trait definition name

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionprocessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/ICamelKModelineOptionValue.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelinePropertyCompletionTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/397

Fusetools2 526 completion for camel component dependency

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/401

Fusetools2 527 completion for maven dependency

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/ICamelKModelineOptionValue.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineCamelComponentDependencyTest.java

FUSETOOLS2-529 - Provide description on hover for Camel component

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKTraitManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitDefinitionNameTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitPropertyNameTest.java

FUSETOOLS2-540 Provide completion for partial trait definition and

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionTest.java

FUSETOOLS2-541 - completion for partial option names in modeline

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperUtil.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOptionTest.java
src/test/resources/workspace/diagnostic/camelk-with-duplicated-traits-in-modeline.java

FUSETOOLS2-535 - provide diagnostic for duplicated traits

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKTraitManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitProperty.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineTraitHoverTest.java

FUSETOOLS2-523 - provide hover for Trait property name

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKTraitManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitProperty.java

see https://sonarcloud.io/organizations/camel-tooling/rules?open=java%3AS1104&rule_key=java%3AS1104
4. Approved PR

Use private attributes

---

src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitDefinitionNameTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitPropertyNameTest.java

Use isEmpty() for improved readability

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesTopLevelCompletionTest.java

FUSETOOLS2-552 - re-add "component" as possible group completion for

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesGroupPropertyCompletionTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/416

Fusetools2 549 provide completion for camel main properties

---

pom.xml

for reference on release process, see contributing guide: https://github.com/camel-tooling/camel-language-server/blob/master/Contributing.md#how-to-release

FUSETOOLS2-561 - prepare for tag 1.1.0

---

.travis.yml

https://github.com/travis-ci/travis-conditions#predicates

FUSETOOLS2-561 - trigger deploy step when it is a build tag

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java

FUSETOOLS2-558 - support insert and replace for Camel component

---

.travis.yml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/CamelDiagnosticMessage.java
src/main/java/com/github/cameltooling/lsp/internal/settings/JSONUtility.java

Fusetools2 608 fix javadocs issues

---

.travis.yml

https://github.com/camel-tooling/camel-language-server/pull/438 to be reviewed and merged first

FUSETOOLS2-608 - ensure javadoc issues detected in pr

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelGroupPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverTest.java

FUSETOOLS2-620 - provide documentation on hover for Camel main options in properties file

---

src/test/java/com/github/cameltooling/lsp/internal/TestExtraComponentUtil.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/AbstractCamelPropertiesComponentOptionTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverTest.java

FUSETOOLS2-621 - provide tests for hover on camel component names and

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java

as recommened by Sonar
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXRTxF33DuP76CgjJng_&open=AXRTxF33DuP76CgjJng_

Remove the literal "false" boolean value

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionprocessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyFileOption.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelPropertyFileTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOptionTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOptionTest.java

it provides completion for properties file that are siblings and in
sibling folders (recursively) of the Camel K file

FUSETOOLS2-537 - provide completion for property-file Camel k modeline

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionprocessor.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetector.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelComponentPropertyTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetectorTest.java

FUSETOOLS2-618 - completion with dashed names for Camel K modeline

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineResourceOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelResourceTest.java

FUSETOOLS2-538 - completion for resource option in Camel K modeline

---

src/test/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/AbstractDiagnosticTest.java

for local execution gaining between 6 and 8 seconds, Total time
decreased from 32-34s to 26s on my machine
4. Approved PR

Improve await conditions to gain test time execution

---

Contributing.md

so that it won'tbe outdated on each Eclipse release.

Provide more generic Eclipse version in contributing guide

---

.settings/Camel Language Server launched with websocket.launch
.settings/Camel Language Server.launch
Contributing.md

- Provide information when using in Eclipse Desktop
- Include Eclipse Launch configurations in project to have them rightly
available and also mention them more easily in contributing guide

Improve Contributing guide for newcomers

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSourcePropertyCompletionTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/473

FUSETOOLS2-670 - completion for camel.source

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelKafkaConnectorTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSinkPropertyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSourcePropertyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorClassCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKafkaConnectorSourceSinkHoverTest.java

Fusetools2 789 hover for camel sink s ource

---

src/main/java/com/github/cameltooling/lsp/internal/completion/AbstractConnectorClassDependentCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/KafkaConnectTransformerTypeCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/KafkaConnectTransformerTypePropertyKeyDetector.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorTransformerCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/KafkaConnectTransformerTypePropertyKeyDetectorTest.java
src/test/resources/camel-kafka-connector-catalog/connector-sink-used-for-test.json

FUSETOOLS2-687 - provide completion for transformers

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/util/ModelHelper.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesEdgeCasesTest.java

recommends to "hide whitespace change" to review the PR as there is a refactor which lead to simply removing one level of indentation for a chunk of code.

FUSETOOLS2-812 - avoid NPE with edge cases in properties completion

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/CamelKafkaConnectorCamelURLRefactor.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/CodeActionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/ConvertCamelKafkaConnectorURLToPropertiesRefactorAction.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaUtil.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/CamelKafkaConnectorCamelUrlRefactorTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java

properties
to be cleaned but wanted to share progress before going on weekend

FUSETOOLS2-685 - Provide refactoring action to convert url to list of

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/model/ApiOptionMethodDescriptorModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/model/ApiOptionMethodsModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/model/ApiOptionModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/model/ApiPropertyMethodOptionModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/model/ApiPropertyOptionModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/model/BaseOptionModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/model/ComponentModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/model/EndpointOptionModel.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/util/ModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/catalog/util/ModelHelperApisTest.java

The model is handcrafted as it was before. it would be interesting to
use a JsonFactory to load everything without the need of the ModelHelper
builder for the future.

FUSETOOLS2-820 - internal catalog model for new apis

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/CamelKafkaConnectorCamelUrlRefactorTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java

FUSETOOLS2-827 - Fix convert to list of properties for path using / not

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/FilterPredicateUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java

FUSETOOLS2-822 - provide api options for Camel URI

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelApiBasedComponentHoverTest.java

FUSETOOLS2-831 - hover on option for API based components

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/494

Fusetools2 829 completion api name

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionprocessor.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineLocalResourceRelatedOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOpenAPIOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyFileOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineResourceOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinitionProperty.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/GenericCamelKModelineOptionValue.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/ICamelKModelineOptionValue.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitDefinitionNameTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitPropertyNameTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineTraitHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOptionTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOptionTest.java
src/test/resources/workspace/diagnostic/camelk-with-duplicated-traits-in-modeline-written-secondline.java

- one part to cover later is to support diagnostic across the lines.
Currently, it only validates line by line
Given the size of the PR, i think it is better to handle it in another task. No regression, it is just another new enhancement.
one example on second line:

FUSETOOLS2-778 - support Camel K modeline on several lines

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/model/ApiOptionModel.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/495

Fusetools2 830 completion method name

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java

FUSETOOLS2-808 - provide completion for jitpack dependency in Camel K

---

src/main/java/com/github/cameltooling/lsp/internal/completion/AbstractConnectorClassDependentCompletionProcessor.java

as recommended by Sonar
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXVBLKYVUMIPP8QeBbRn&open=AXVBLKYVUMIPP8QeBbRn

Change visibility of abstract class to protected

---

.circleci/config.yml

FUSETOOLS2-866 - First Circle CI iteration: simple build with test for

---

.circleci/config.yml
pom.xml

requires https://github.com/camel-tooling/camel-language-server/pull/507 and https://github.com/camel-tooling/camel-language-server/pull/506
and to have a bunch of environment variables setup in CircleCI config (not yet done)

FUSETOOLS2-866 - third iteration publish snapshots

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java

parameters
it allows to have distinct icons on client side

FUSETOOLS2-888 - use specific completion item kind for api based uri

---

.circleci/config.yml

see how it is displayed in case of failure https://app.circleci.com/pipelines/github/camel-tooling/camel-language-server/72/workflows/cf7fe7c5-4645-43e9-8ccb-0422d527dec2/jobs/225/tests
see how it is displayed in success https://app.circleci.com/pipelines/github/camel-tooling/camel-language-server/72/workflows/f9a48efd-4280-492e-98dc-10cab1b09eef/jobs/223/tests

FUSETOOLS2-866 - store test results

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java

when method name is not specified

FUSETOOLS2-897 - avoid NPE calling completion for API based components

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/RequiredErrorMsg.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/EndpointDiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-missing-methodname.xml

FUSETOOLS2-899 - support new type of error reported "required"

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentSchemesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java

https://sonarcloud.io/project/issues?assignees=lhein%40github&id=camel-lsp-server&open=AXDJ05xgvjqUPhCxeFiZ&resolved=false
https://sonarcloud.io/project/issues?assignees=lhein%40github&id=camel-lsp-server&open=AXDJ05z8vjqUPhCxeFia&resolved=false

Use Format specifiers instead of string concatenation for logger

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorPropertiesDiagnosticTest.java
src/test/resources/workspace/diagnostic/ckc-sink-invalid-mix-url-and-endpoint.properties

FUSETOOLS2-912 - diagnostic error when mix of url and normal attributes

---

src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorOfficialExamplesDiagnosticTest.java

specific Camel Kafka Connector example repository
/!\ currently, there is no 0.6.1 tag or 0.6.x branch on Camel Kafka
Connector example repository so using the master. it will be a bit more
sensible in case of issues upstream but should be ok as a first
iteration.
4. Approved PR

FUSETOOLS2-917 - provide tests for diagnostic on examples part of

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSourcePropertyCompletionTest.java
src/test/resources/camel-kafka-connector-catalog/connector-source-used-for-test.json

FUSETOOLS2-819 - insert default value for Camel Kafka Connector

---

pom.xml
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionInsertAndReplaceTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineComponentPropertyHoverTest.java
src/test/resources/workspace/diagnostic/camel-valid.properties
src/test/resources/workspace/diagnostic/camel-with-boolean-error.properties
src/test/resources/workspace/diagnostic/camel-with-integer-error.properties

needs to adjust few tests due to Catalog updates

FUSETOOLS2-928 - upgrade to Camel 3.7.0

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/util/CamelKafkaConnectorCatalogManager.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelGroupPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaUtil.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorBasicPropertiesCompletionTest.java

FUSETOOLS2-849 - provide completion for basic Camel kafka Connector

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelKafkaConnectorClassCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorClassCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKafkaConnectorConnectorClassHoverTest.java
src/test/resources/camel-kafka-connector-catalog/connector-source-used-for-test.json

FUSETOOLS2-814 - provide description for connector.class values

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/EndpointDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolJavaProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java

when computing DocumentSymbol and Diagnostic

FUSETOOLS2-937 - avoid exception for invalid java file

---

README.md
pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/runtimeprovider/CamelRuntimeProvider.java
src/main/java/com/github/cameltooling/lsp/internal/settings/SettingsManager.java
src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogRuntimeProviderTest.java

FUSETOOLS2-961 - Provide a setting to set a Runtime Provider

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/util/StringUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentParameterPropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelGroupPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/catalog/util/StringUtilsTest.java

ending with dash
see https://issues.apache.org/jira/browse/CAMEL-16250

FUSETOOLS2-1011 - workaround StringHelper.dashToCamelCase for name

---

src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorOfficialExamplesDiagnosticTest.java

given that upstream project deleted the 0.7.2 branch

FUSETOOLS2-1015 - use tags

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/AbstractDocumentSymbolProcessor.java

format
not found the use case that created the NumberFormatException so
providing more details in case it happens again so that the use can be
detected.

FUSETOOLS2-986 - provide more information in case of invalid number

---

src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java

as recommended by Sonar
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXYZ0sg4VEJUvx7Dhpf-&open=AXYZ0sg4VEJUvx7Dhpf-

Provide parameterized test

---

README.md
src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/CamelWorkspaceService.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/AbstractQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/InvalidEnumQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/KafkaTopicCompletionProvider.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamKeyURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamValueURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/main/java/com/github/cameltooling/lsp/internal/settings/SettingsManager.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KafkaTopicCompletionTest.java

completion
most of the changes are related to the fact that the SettingsManager needs to be available when doing the completion to have access to the Kafka Connection URL setting.
see video here https://youtu.be/e4dkV8YhSoE

FUSETOOLS2-1059 - provides setting for Kafka Connection url used for

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java

FUSETOOLS2-1066 - changed notation for modeline dependency completion

---

src/main/java/com/github/cameltooling/lsp/internal/completion/KameletTemplateIdCompletionProvider.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KameletCompletionTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/590

Fusetools2 1103 kamelet catalog completion with description

---

src/main/java/com/github/cameltooling/lsp/internal/completion/KameletTemplateIdCompletionProvider.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KameletCompletionTest.java

FUSETOOLS2-1104 - filter completion of kamelet template id by

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelURIHoverFuture.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelURIHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamKeyURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamValueURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/test/java/com/github/cameltooling/lsp/internal/hover/KameletHoverTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/593 --> MERGED
requires https://github.com/camel-tooling/camel-language-server/pull/596

Fusetools2 1105 hover for kamelet

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KameletCompletionTest.java

requires https://github.com/camel-tooling/camel-language-server/pull/600

Fusetools2 1136 kamelet option completion with default value inserted

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java

reported as code smell by Sonar
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXl5ZFhkVESRShQyETth&open=AXl5ZFhkVESRShQyETth

Use method reference when possible

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/hover/KameletHoverTest.java

FUSETOOLS2-1135 - added hover doc for kamelet properties

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java

see https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXoZ9O-dTKya_KffcyJR&open=AXoZ9O-dTKya_KffcyJR

Replace lambda with a method reference

---

src/test/java/com/github/cameltooling/lsp/internal/hover/KameletHoverTest.java

see https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXoZ9PK8TKya_KffcyJS&open=AXoZ9PK8TKya_KffcyJS

use parameterized test to simply reading and maintenance

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionTest.java

FUSETOOLS2-1178 - include new Option names for modeline

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionTest.java

FUSETOOLS2-1181 - deprecate property-file modeline

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/CodeActionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/ConvertCamelKPropertyFileModelineRefactorAction.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ILineRangeDefineable.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKModelineParser.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/CamelKPropertyFileModelineDeprecatedRefactorTest.java

FUSETOOLS2-1183 - quickfix convertproperty file

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java

see https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXovPxLwuIR_c8jsNd1M&open=AXovPxLwuIR_c8jsNd1M

Reduce Cognitive complexity in CamelOptionNamesCompletionFuture

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelComponentPropertyTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelinePropertyTest.java

FUSETOOLS2-1180 - include file: as completion for value of property

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyDashFileOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelPropertyFileTest.java

property=file: Camel K modeline option

FUSETOOLS2-1185 - provide file system resource completion for

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineConfigOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineConfigOptionTest.java

FUSETOOLS2-1186 - provide kind possibilities on config option for Camel

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineConfigFileOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineConfigOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineConfigOptionTest.java

FUSETOOLS2-1187 - completion for config=file: based on local filesystem

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineResourceFileOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineResourceOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelOpenAPITest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelResourceTest.java

FUSETOOLS2-1182 - Adapt resource modeline option to new API

---

src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogVersionTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelExtraComponentTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionInsertAndReplaceTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionBooleanValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionEnumerationValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionsCompletionsTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelDeprecationIndicatorInCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointOptionDuplicateTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointUriCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelLanguageServerCompletionPositionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KafkaTopicCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KameletCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelApiBasedComponentHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/KameletHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/util/RouteTextBuilder.java

factorized only the part with single uri with a from for blueprint and
spring in xml (which is the most used)

FUSETOOLS2-1166 - factorize creation of camel route used in test

---

src/main/java/com/github/cameltooling/lsp/internal/telemetry/OS.java

see https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXrDWusMzX0kCOJvl040&open=AXrDWusMzX0kCOJvl040

Remove useless transient modifier

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/util/CamelNodeDetailsUtils.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/AbstractDocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/folding/FoldingRangeProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/folding/FoldingRangeRouteTest.java

FUSETOOLS2-1231 - provide folding range for routes written in Java

---

.circleci/config.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/maven.yml
pom.xml
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java

* update build configuration and information
* update the default value for jitpack completion too
before merging needs to update the default branch in GitHub Web UI and to synchronize with QE so that their CI is ready to be updated.

FUSETOOLS2-1294 - Migrate default branch name from master to main

---

Contributing.md

it avoids to be sensitive to branch name

Use relative link for file inside repository

---

Contributing.md

updating reference in our readme
see also https://github.com/eclipse/lsp4j/issues/567

LSP4J has changed master branch to main

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentSchemesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogRuntimeProviderTest.java

for instance when a component is declared but definition is not
provided. https://issues.apache.org/jira/browse/CAMEL-17146

FUSETOOLS2-1351 - workaround potential error in Camel Catalog

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/ConnectedModeDiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/ConnectedModeDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-kafka-endpoint.java
src/test/resources/workspace/diagnostic/camel-with-kafka-endpoint.xml

FUSETOOLS2-1414 - provide hint for connected mode for Kafka

---

pom.xml

this PR is the step #3 of current release procedure https://github.com/camel-tooling/camel-language-server/blob/main/Contributing.md#how-to-release

Remove SNAPSHOT from version to do a release

---

src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelDeprecationIndicatorInCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointOptionDuplicateTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointUriCompletionTest.java

as suggested by Sonarcloud
https://sonarcloud.io/project/issues?resolved=false&severities=MINOR&types=CODE_SMELL&id=camel-lsp-server

Leverage better AssertJ methods

---

pom.xml

Updated pom to 1.6 version

---

pom.xml

Bump version to 1.7.0 SNAPSHOT

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineFileType.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineInsertionTest.java

'^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$'.
https://sonarcloud.io/project/issues?issues=AYHIWiy3QPuvMBA4ED2k&open=AYHIWiy3QPuvMBA4ED2k&id=camel-lsp-server

Rename constant name to match the regular expression

---

.github/workflows/jdk19.yml

remove Java 18 as it is not an LTS, just test with latest stable release

Use Java 19 in CI

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java

In case, a diagnostic was requested, then a clear request is coming (through closing editor). If the diagnostic was taking some time, the server was responding first the clear request and then the response for the first diagnostic. So client will have the wrong last state requested.
With this PR, it is ensuring that currently running request are cancelled before clearing.
It was causing the test
CamelDiagnosticTest.testValidationErrorClearedOnClose() to be flaky

FUSETOOLS2-1505 - cancel previously launched diagnostic when clearing

---

.circleci/config.yml
.github/workflows/jdks.yml

FUSETOOLS2-1907 - Build matrix of JDKs on GitHub Actions instead of

---

.github/workflows/main.yml
pom.xml

it is required to deploy released version (but not snapshots!!) increased version to 1.9.1 then
4. Approved PR

Fix generation of sources and javadoc

---

.github/workflows/jdks.yml

FUSETOOLS2-2008: Support Java 20

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionValuesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/TwitterTimelineCompletionTest.java

feature: Completion for Twitter lang values (ISO_639-1)

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/VSCodeTasksCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/traits/CamelKTraitManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/traits/TraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/completion/traits/TraitProperty.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinitionProperty.java
src/test/java/com/github/cameltooling/lsp/internal/completion/VSCodeTasksJsonTest.java

https://github.com/camel-tooling/camel-language-server/assets/1105127/e3ca48d0-65bb-458a-95f4-9df29391e159

2182 completion for VS code tasks json

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionValuesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelKubernetesServicesCompletionTest.java

Continue with #990 now we can also detect configmaps.
[Screencast from 2023-10-10 12-19-48.webm](https://github.com/camel-tooling/camel-language-server/assets/726590/c03020ae-bd5b-4328-a57c-d8aa7750e79f)

feature: Auto-completion for kubernetes configmaps

---

.github/workflows/jdks.yml

* removing Java 20 which is not an LTS

Test with JDK 21

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/CamelKGroovyDSLFileParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/CamelKJSDSLFileParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/CamelKKotlinDSLFileParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/CamelYamlDSLFileParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/JavaFileParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/Parser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/ParserChainOfResponsibility.java
src/main/java/com/github/cameltooling/lsp/internal/parser/fileparserhelper/XMLFileParser.java

**getCorrespondingParserFileHelper** method of **ParserFileHelperFactory** class refactored for cognitive complexity.
Multiple if-else condition block of code changed with **Chain Of Responsibility** Pattern
Fixed #316

Issue#316 : ParserFileHelperFactory Class Refactored

---

pom.xml

Prepare release 1.17.0

---

pom.xml

Prepare next development iteration 1.18.0-SNAPSHOT

---

pom.xml

They need to be updated at the same time

Upgrade citrus and kafka

---

pom.xml

Kafka and citrus upgrade

---

pom.xml

Prepare release 1.27.0

---

pom.xml

Prepare next development iteration 1.28.0

---

.github/workflows/main.yml
pom.xml

* https://central.sonatype.org/news/20250326_ossrh_sunset/#questions
* https://central.sonatype.org/faq/what-is-different-between-central-portal-and-legacy-ossrh/
I updated the tokens in the settings of the github repository

FUSETOOLS2-2584 - migrate from OSSRH to Central

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/catalog/runtimeprovider/CamelRuntimeProvider.java
src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogRuntimeProviderTest.java

the last catalog is still in 3.x version

Remove Karaf runtime provider support
