camel-tooling/camel-language-server

pom.xml

notable features:
- more accurate coverage
- Java 9 and 10 supports

Upgrade jacoco from 0.7.9 to 0.8.1

---

.travis.yml

after migration to a splitted repository, several parameters are no more
useful for the server itself

#5 - clean travis.yml

---

src/main/java/com/github/cameltooling/lsp/internal/AbstractLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/CamelWorkspaceService.java

- use {} instead of {0} whcih is the correct usage with slf4j logger
- use parameters for log methods which avoids creating String in case
the level of log is not enabled

Fix sonar code smell

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java

- allows to find routes more easily
- in VS Code Ctrl+Shift+O
- in Eclipse Desktop with LSP4E provides an outline and with 
- limitation: the SymbolKind used is "Field", there is currently an
hardcoded set of possible symbol kind, none are really matching "Camel
routes"

#73 - support DocumentSymbol for Camel routes

---

pom.xml

see release note:
http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-3.10.0

Upgrade AssertJ from 3.9.1 to 3.10.0

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/DSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/JavaDSLModelHelper.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/XMLDSLModelHelper.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java

the only spotted difference for now is the &amp;
there is also the preparation for the producer computation, some
information will be needed when parsing the enclosing elements of the
Camel uri string
Please note that nothing is visible yet from the interface, this is only internal work to support Java later

#92 - Support java and xml writing of Camel uri in internal model

---

src/test/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstanceTest.java

#93 - fix test to avoid being dependent on JVM list internal order

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java

it it a "false-positive" in our context because we need to have it to be
compatible with the API of a dependency.
see https://groups.google.com/d/msg/sonarqube/BLXAdLEL9QE/UuErZS6oAgAJ

Suppress warning for Sonar rule on Generic wildcard types

---

src/main/java/com/github/cameltooling/lsp/internal/hover/HoverProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java

which was previously done to workaround
https://github.com/eclipse/lsp4j/issues/172

Return no hover instead of empty hover

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelperTest.java

and write test checking that the newly used specifier is the right one
issue was reported by Sonar: https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AWUYoqhLopYCBC6oaqes&open=AWUYoqhLopYCBC6oaqes

Fix format specifier of Logger

---

pom.xml

to workaround the fact that lsp4j is declaring aversion range dependency
and that on CI it is trying to take a SNAPSHOT version and failing

Specify xtend.lib version (#140)

---

src/main/java/com/github/cameltooling/lsp/internal/AbstractLanguageServer.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerRobustnesstest.java

- in case stopServer is called before a startServer
- added start and stop in tests
- thanks to previous test detected and fixed a remaining Java thread
when stop server called

Improve robustness against wrong call order (#165)

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java

making the diagnostics computation async #116

---

src/main/resources/log4j.properties

it avoids to have the log file created in the project of the user

Move log file to tmp folder #174

---

.travis.yml

the code is launched only on master
should fix the master build for the sonar analysis part which was failing this way:
```
$ if [[ $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "master" && $IS_SNAPSHOT == "true" || -n "$TRAVIS_TAG" && $IS_SNAPSHOT == "false" ]]; then mvn test -P !build-extras -B mvn sonar:sonar -Dsonar.login=${SONAR_TOKEN} -Dsonar.organization="camel-tooling" -Dsonar.projectKey="camel-lsp-server" -Dsonar.projectName="Camel LSP Server"; fi
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO] Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-p …
```

Add missing semicolon in the multi-line script #153

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java

re-reparsing the uri as Camel still not providing the start and end
character
now on the Camel URI instead of the full line:

Improve range position of diagnostic #113

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java

camel-tooling/camel-lsp-client-eclipse#44
- it avoids to open a console, and so avoid the problem of nto closing
console
- the logs were trying to give a bit of information on language Server
state but in fact end users doesn't really care, it is useful more for
debugging purpose
4. Approved PR

Remove log sent from server to client

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-properties.xml
src/test/resources/workspace/diagnostic/camel-with-unknownParameter-forlenientcomponent.xml
src/test/resources/workspace/diagnostic/camel-with-unknownParameter.xml

Some Camel components have "lenient" properties. It means that they can
have custom parameters. These parameters were reported as "unknown
parameter" although they are valid.
provided a test for using toD and Camel global properties and set it as
@Ignore waiting for a fix at Camel level. see CAMEL-13382
4. Approved PR

Avoid false positive for "lenient" properties #220

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelApplicationPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaConnectDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperUtil.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserJavaFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelApplicationPropertiesTopLevelCompletionTest.java
src/test/resources/workspace/application.properties

- it allows to setup the mechanism for application.properties
- it has hardcoded 3 values only for now
- includes a small refactor to extract some useful methods of
ParserHelper

provide initial top-level completion for application.properties #264

---

.travis.yml

Exclude dependabot branches from non-PR jobs #286

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelApplicationPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentIdsCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelApplicationPropertiesComponentCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelApplicationPropertiesTopLevelCompletionTest.java

the completion is only when calling right after the dot.
requires https://github.com/camel-tooling/camel-language-server/pull/265 --> DONE

266 completion for components id in application.properties

---

README.md
pom.xml
src/main/java/com/github/cameltooling/lsp/internal/Runner.java
src/main/java/com/github/cameltooling/lsp/internal/websocket/CamelLSPWebSocketEndpoint.java
src/main/java/com/github/cameltooling/lsp/internal/websocket/CamelLSPWebSocketServerConfigProvider.java
src/main/java/com/github/cameltooling/lsp/internal/websocket/WebSocketRunner.java
src/test/java/com/github/cameltooling/lsp/internal/RunnerWebSocketTest.java

- use Tyrus, the reference implementation
- connection through non-configurable port 8025
- camel server jar needs to launched with --websocket
no test, I don't know yet how to write test for it :-(

Provide websocket support #260

---

src/test/java/com/github/cameltooling/lsp/internal/RunnerStandardIOTest.java

camel-tooling/camel-lsp-client-vscode#142
it was removed during refactor for Websocket but it was not intended.
Added a test to avoid regression in the future for this very specific
point. Issue was caught by UI tests in client side.
4. Approved PR

register client proxy to the server

---

src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKYamlDSLParser.java
src/test/java/com/github/cameltooling/lsp/internal/parser/CamelKYamlDSLParserTest.java

- reported by Sonar
- created test for this piece of code and discovered that the case of
backslash is not handled. Created #301 to handle it
4. Approved PR

Fix potential NPE #296

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-2-unknownParameters.xml
src/test/resources/workspace/diagnostic/camel-with-unknownParameterAndAnotherError.xml

not covered cases:
- multiline Camel URI
- unknown option which is a substring of another parameter on the same
line
please note that it would be better to have Camel validation result
returning a more precise range directly instead of calculating on
Language Server side
4. Approved PR

FUSETOOLS2-67 - provide more precise Diagnostic range for unknown option

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-invalid-enum-with-same-string-in-camel-uri.xml
src/test/resources/workspace/diagnostic/camel-with-invalid-enum.xml
src/test/resources/workspace/diagnostic/camel-with-several-errors-with-precise-specific-range.xml

- doesn't handle multi-line
- doesn't handle cases of property name AND property enum value are
repeated in the same Camel URI (which seems highly improbable). it
handles the case of repeated property enum values
4. Approved PR

FUSETOOLS2-73 - Provide precise range for wrong enum values

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfix.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-unknownParameter.xml

based on LevenshteinDistance: This is the number of changes needed to
change one sequence into another, where each change is a single
character modification (deletion, insertion or substitution).
in case there is no "similar" properties. I implemented to provide no quickfix.
Would it be better to provide all possible properties even if the list can be very very long (several hundreds)?
4. Approved PR

FUSETOOLS2-69 - limit quickfix for unknown properties to "similar" ones

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesTopLevelCompletionTest.java

previously only application.properties were supported for camel.xxx and
all names for Kafka full Camel URI completion.
now all properties files are supported with camel.xxx, keeping the
support of full Camel URI support for specific source and sink Camel
Kafka Connect
4. Approved PR

FUSETOOLS2-82 - all properties files are supported

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyFilekey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaConnectDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaUtil.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyFileEntryInstanceTest.java

- allows to remove CamelKafkaConnectDSLParser from CamelPropertyFiles
model
- introducing the representation of property values in the model
4. Approved PR

FUSETOOLS2-132 - refactor Property model

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOptionTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTest.java

No impact on external behavior. It is the first piece to be able to
provide support for modeline. Now that there is a model for it we will
eb able to provide it. The model will surely evolve to handle completion
in Option Values but it can be done later to keep small chunks of code.
- parse into a model taking care of position with options
- handling modeline for all supported languages (yaml and xml are
special cases compared to others)
- keep same level of constraints than before in terms of space around
"// camel-k: " and "# camel-k: ". the Runtime allows to write
""//camel-k:" for instance. this can be improved in another task. it
wasn't the goal of this one.
- support space and tab character between options. The runtime is using
a regexp which seems to allow \r \n and \f but it will …

FUSETOOLS2-512 - first iteration to parse modeline

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelKModelineCompletionprocessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModeline.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKModelineParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/393
- hardcoded list for now. The "useful" ones, as mentioned in Camel K
documentation, are not available dynamically for now anyway.
- it is providing completion only at the end of a modeline, not in the
middle

FUSETOOLS2-513 - provide completion for top level modeline options

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitProperty.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitPropertyNameTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/397

Fusetools2 520 provide completion for trait property name with default value

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentIdsCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionValuesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentNamePropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentParameterPropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/GenericCamelKModelineOptionValue.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesTopLevelCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelComponentPropertyTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstanceTest.java

it is reusing the work initially done for application.properties and
Camel Kafka properties files

FUSETOOLS2-528 - Provide Camel Component property completion in modeline

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesTopLevelCompletionTest.java

FUSETOOLS2-547 - add new top-level, named as group, for Camel component

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelURIHoverFuture.java
src/main/java/com/github/cameltooling/lsp/internal/hover/CamelURIHoverProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentNamePropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentParameterPropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineComponentPropertyHoverTest.java

FUSETOOLS2-530 - Provide hover for Camel Component Property in Modeline

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesTopLevelCompletionTest.java

based on https://github.com/camel-tooling/camel-language-server/pull/415
nota: given that 3.4.0 had regressions, the default Camel Catalog is still 3.3.0 and thus less items are provided in completion than on current master, but it is more accurate as respecting the Camel version.

Fusetools2 548 use catalog file for application properties

---

pom.xml

- version from xtend
https://github.com/eclipse/lsp4j/blob/328ce8a4c89b0cd84fb62118f459b6cf79b09e90/gradle/versions.gradle#L16
- it allows to get rid of
https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236?utm_medium=Partner&utm_source=RedHat&utm_campaign=Code-Ready-Analytics-2020&utm_content=vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236

Align xtend library with the one used by lsp4j

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKTraitManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/TraitProperty.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinitionProperty.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitDefinitionNameTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineTraitPropertyNameTest.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitOptionTest.java

- side-effect to workaround limitations of VS Code which was causing
completion for traits not working in yaml
- also inserts "." after definition name if not present

FUSETOOLS2-558 - use insert and replace for Camel K modeline traits

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesTopLevelCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelComponentPropertyTest.java

- side-effect to workaroud limitations of VS Code which was causing
completion for "camel" and groups not working in yaml
- also inserts "." after inserted text when needed

FUSETOOLS2-558 - use insert and replace for Camel properties

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/InvalidDurationErrorMsg.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/EndpointDiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/AbstractDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java

also improved test to check that there is no diagnostic with empty
message. The diagnostic in this case is not very useful and they are
ignored in VS Code UI.

FUSETOOLS2-504 - add support for new duration error type

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java

it adds the insert-and-replace and also it workarounds the bad behavior
of VS Code which is filtering out completion items without range/text
Edit when some others completion have it.

FUSETOOLS2-527 - add insert and replace for mvn dependency completion

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/settings/JSONUtility.java

which I introduced with previous commit :'(
```
[ERROR] /home/travis/build/camel-tooling/camel-language-server/src/main/java/com/github/cameltooling/lsp/internal/settings/JSONUtility.java:31: error: unknown tag: T
[ERROR] 	 * @return the object converted in the <T> type
```
not foudn yet why the stage test is not detecting it (need to fix that too in another PR to avoid this boring errors failing on master only)

FUSETOOLS2-608 - fix javadoc

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentParameterPropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetector.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/AbstractCamelPropertiesComponentOptionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesComponentOptionDashedNameCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetectorTest.java

the choice to provide dashed or camelCase name is based on the other
parts of the file. if there is already dashed name, it is proposing
dashed ones, otherwise, it is proposing Camel cased ones
see [subtasks of story](https://issues.redhat.com/browse/FUSETOOLS2-550) for several follow-up cases

FUSETOOLS2-616 - support completion for dashed name of component options

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelGroupPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetector.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelPropertiesGroupPropertyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetectorTest.java

properties file
when there is already a dashed name in the same file

FUSETOOLS2-619 - completion with dashed name for main options in

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentParameterPropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelGroupPropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverTest.java

depends on https://github.com/camel-tooling/camel-language-server/pull/445

Fusetools2 617 doc on hover for dashed name of component options

---

src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineOptionNames.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineLocalResourceRelatedOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOpenAPIOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineResourceOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelOpenAPITest.java

filters on json, yaml and yml files as a first iteration. We don' tknow
yet what is the precise filter for Open APi spec v2.

FUSETOOLS2-536 - provide completion for open-api in Camel K modeline

---

.travis.yml

15
replacing Java 14 as it is not a LTS (Long Term Support)

FUSETOOLS2-627 - upgrade one test stage on Travis from Java 14 to Java

---

README.md
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineLocalResourceRelatedOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOpenAPIOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyFileOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineResourceOption.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelOpenAPITest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelPropertyFileTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCamelResourceTest.java

when providing completion for resource-like Camel K modeline properties.
list is currently limited to 3 IDEs and the most common folder for a Camel K project

FUSETOOLS2-707 - filter out files in IDE config folders

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolJavaProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolXMLProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/resources/workspace/My3RoutesBuilder.java

- first iteration allowing to have a high-level overview
- ideas for future:
- includes when/otherwise information
- provide route id if available
- provide component name
/!\ tricky part in VS Code. By default, the outline is sorting by "category" (why the hell??) needs to change to sort by position to have a better overview of the flow. The Language Server is providing the right information. After it is a problem of the Client implementation that is choosing how to display stuff. In this case, their outline is not really meant to display a flow unfortunately.
Well, even with this choice, it remains convenient to have the route available in outline with their children elements.

FUSETOOLS2-717 - Provide Document Symbol for Java DSL

---

src/test/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/BooleanErrorMsgTest.java
src/test/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/EnumErrorMsgTest.java
src/test/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/IntegerErrorMsgTest.java
src/test/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/NumberErrorMsgTest.java
src/test/java/com/github/cameltooling/lsp/internal/catalog/diagnostic/ReferenceErrorMsgTest.java
src/test/java/com/github/cameltooling/lsp/internal/catalog/util/ModelHelperTest.java

after merge from common, it is now in the same package, so no need to
import it

Remove unused import

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolJavaProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java

limitation: doesn't support having several level of camel nodes on the same line. I have nerver seen a route written this way. so thought to be okay to not handle it

FUSETOOLS2-719 - include component path in outline for Java DSL

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolJavaProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/resources/workspace with space/MyRouteBuilder.java

path
to check:
- create folder with a space
- create a Camel Java file in it
- ensure an access oto document symbol is done (for instance by accessing outline)

FUSETOOLS2-735 - avoid NPE in Document Symbol when there is a space in

---

src/main/java/com/github/cameltooling/lsp/internal/hover/CamelURIHoverFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ILineRangeDefineable.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentNamePropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelComponentParameterPropertyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelGroupPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinition.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTraitDefinitionProperty.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineCamelComponentDependencyTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineComponentPropertyHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineOptionNamesHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKModelineTraitHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelLanguageServerHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverTest.java

- it ensures clients to correctly updates the tooltip when several
language servers are contributing hovers on the same parts. (especially
Eclipse Desktop)
- it potentially avoids recalling the language server by the client when
the hover for the range was already provided.
on master without this PR:
with this PR:

FUSETOOLS2-755 - Provide range on Hover

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelKafkaConnectorClassCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaUtil.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorClassCompletionTest.java

which is a specific Camel Kafka Connector property.
This is the first completion relying on the Camel Kafka Connector
Catalog.
Currently using a snapshot version as it is not part of a released
version
--> ~need to wait for Camel kafka Connector artifact to be published on Apache Snapshot repository (nightly build)~ done
--> Are we fine to use a snapshot version? or we wait fo ra release? if using snapshots, it will allow to go further more easily on other tasks related to Camel Kafka Connector. Other possibilities are to have a myriad of other PR or to create a feature branch (but needs to check how to setup the CI  for that). Or we can also wait for an official release for goign further (no date planned as far as I know)

FUSETOOLS2-774 - provide completion for connector.class

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkPropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSinkPropertyCompletionTest.java

user needs to type camel.sink. and the connector.class property value
must be provided and part of the Catalog.
Should come soon in next Pull Requests:
- same for camel.source
- a centralized Camel Kafka Connector Catalog to factorize code and test
more easily

FUSETOOLS2-670 - Provide completion for Camel Sink properties

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/util/CamelKafkaConnectorCatalogManager.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelKafkaConnectorClassCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/AbstractCamelKafkaConnectorTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSinkPropertyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSourcePropertyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorClassCompletionTest.java
src/test/resources/camel-kafka-connector-catalog/connector-sink-used-for-test.json
src/test/resources/camel-kafka-connector-catalog/connector-source-used-for-test.json

requires https://github.com/camel-tooling/camel-language-server/pull/474 and https://github.com/apache/camel-kafka-connector/pull/588 (and a nightly build after merge of PR)
use a single of CamelKafkaConnectorCatalog
- it allows to have test independent of Catalog version
- it allows to add specific connector in catalog to test more easily
- requirements to allow handle several version of the catalog
- requirements to let users provide their own connector definition
(which requires more work)

FUSETOOLS2-788 - use a single instance of CamelKafkaConnector by Camel Language Server instance

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelKafkaConverterCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKafkaUtil.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorConverterCompletionTest.java
src/test/resources/camel-kafka-connector-catalog/connector-sink-used-for-test.json

requires https://github.com/camel-tooling/camel-language-server/pull/475
nota: the completion is not very readable in VS Code. I woudl prefer to handle it in a specific PR https://issues.redhat.com/browse/FUSETOOLS2-801

FUSETOOLS2-686 - completion for converters

---

src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/resources/workspace/PartialRoute.java

Fusetools2 739 add test for partial route in java for document symbol

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/AbstractDocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolJavaProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolXMLProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java

- it has kind of redundant imbrication for route/from but I preferred to
keep it as-is. It stays closer to Java outline. I think it is
interesting in outline, it allows to have different details. it is not
very nice with Ctrl+shift+O as it highlights the whole content route and
not just the from. That said, there is also the "from" highlighting only
the from line with the xml Document symbol which is usually also
installed. I do not clear advantages for one or the other option. So
picked the one easiest to maintain and better for the outline instead of
the Document symbol search which is a less visible feature.

FUSETOOLS2-721 - outline of Camel endpoints for XML

---

src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineOption.java
src/test/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineTest.java

the xml comment tag and the content of Camel k modeline
one noticeable impact is with completion:

FUSETOOLS2-558 - fix insert and replace when there is no space between

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetector.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSinkPropertyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaCamelSourcePropertyCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelKafkaConnectorSourceSinkHoverTest.java
src/test/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/DashedCaseDetectorTest.java

FUSETOOLS2-787 - support dashed notation for camel.sink and camel.source

---

src/main/java/com/github/cameltooling/lsp/internal/completion/AbstractConnectorClassDependentCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelKafkaConnectorClassCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CompletionItemCreator.java
src/main/java/com/github/cameltooling/lsp/internal/completion/FilterPredicateUtils.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorClassCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorConverterCompletionTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/camelapplicationproperties/CamelKafkaConnectorTransformerCompletionTest.java
src/test/resources/camel-kafka-connector-catalog/connector-sink-used-for-test.json

- use simple name in label
- use fully qualified name in details

Fusetools2 801 provide more useful display of class names

---

src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineDependencyCompletionTest.java

it was due to merge collision without conflict.
in one PR, several tests were modified to adapt to new behavior.
in a second PR, a test was added without benefiting from the modification of the first one.

FUSETOOLS2-808 - fix test

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentIdsCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionNamesCompletionFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelComponentSchemesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CompletionResolverUtils.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelGroupPropertyKey.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineDependencyOption.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelDeprecationIndicatorInCompletionTest.java

- continue to also use the deprecated "deprecated" field so that it is
also working on clients that have not upgraded yet.

FUSETOOLS2-817 - support new way to specify deprecation

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/test/java/com/github/cameltooling/lsp/internal/TestExtraComponentUtil.java
src/test/java/com/github/cameltooling/lsp/internal/hover/CamelPropertiesFileHoverTest.java

Fusetools2 835 hover for camel url in properties file

---

.circleci/config.yml

requires https://github.com/camel-tooling/camel-language-server/pull/506
- use context sonarcloud which is providing SONAR_TOKEN
- compared to Travis, requires to specify the sonar.host.url

Fusetools2 866 second iteration sonar on master

---

cd/before-deploy.sh

as mentioned here
https://superuser.com/questions/1325862/gnupg2-suddenly-throwing-error-building-skey-array-no-such-file-or-directory
newer versions requires it.
missed the transfer of it from the test branch https://github.com/camel-tooling/camel-language-server/commit/46da62c5d3d2c01dc696e36658680f0eed0a7842

FUSETOOLS2-866 - add --batch to gpg

---

.travis.yml

the configuration for deployment between Circle CI and Travis are
different and incompatible. need to choose one to do it.
if wee need to switch back, this commit can be reverted
I do not see easy solution to keep both working at same time.
Would need:
- specific Maven profile activated or not depending on the CI
- different script called for the crypting key (this one sounds easier)
I do no think that it is worthy to maintain both. It would publish a build based on the same commit two times anyway keeping them both.
But if disagree, can work to provide both working.

FUSETOOLS2-866 - remove deploy from travis

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/EndpointDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolJavaProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/documentsymbol/DocumentSymbolProcessorTest.java
src/test/resources/workspace/AnInterface.java
src/test/resources/workspace/diagnostic/AnInterface.java

- avoid in document symbol
- avoid in Diagnostic service
initial issue reported by user https://github.com/camel-tooling/camel-lsp-client-vscode/issues/475

FUSETOOLS2-885 - avoid ClassCastException for interface java file

---

src/main/java/com/github/cameltooling/lsp/internal/documentsymbol/AbstractDocumentSymbolProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelineLocalResourceRelatedOption.java

class
Abstract classes should not have public constructors. Constructors of
abstract classes can only be called in constructors of their subclasses.
So there is no point in making them public. The protected modifier
should be enough.
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXVRD0WrqCk3s3qSG0pX&open=AXVRD0WrqCk3s3qSG0pX
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXUIOHL-67TsbFDQSkwe&open=AXUIOHL-67TsbFDQSkwe
https://sonarcloud.io/project/issues?id=camel-lsp-server&issues=AXWTt_LjtgwF3nOez880&open=AXWTt_LjtgwF3nOez880

Change the visibility of the constructor to "protected" for abstract

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java

FUSETOOLS2-896 - configure sort text to have API based options first in

---

src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionForApisTest.java

fix incompatible test update between https://github.com/camel-tooling/camel-language-server/pull/519 and https://github.com/camel-tooling/camel-language-server/pull/520
see broken master https://app.circleci.com/pipelines/github/camel-tooling/camel-language-server/86/workflows/6157f29d-8593-4e4e-b9a9-d31818b77dee/jobs/277

FUSETOOLS2-896 - adapt test to modifications done in another PR

---

.circleci/config.yml

java 11
see https://sonarcloud.io/documentation/appendices/end-of-support/

Sonar will soon end support of analysis done with Java 8, so do it with

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/util/CamelKafkaConnectorCatalogManager.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKModelineDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/ConfigurationPropertiesDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/EndpointDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorPropertiesDiagnosticTest.java
src/test/resources/workspace/diagnostic/ckc-sink-invalid-property.properties
src/test/resources/workspace/diagnostic/ckc-sink-valid-dashed-case.properties
src/test/resources/workspace/diagnostic/ckc-sink-valid-url.properties
src/test/resources/workspace/diagnostic/ckc-sink-valid.properties

FUSETOOLS2-815 - provide validation for invalid camel.(source|sink)

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/AbstractDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorOfficialExamplesDiagnosticTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorPropertiesDiagnosticTest.java
src/test/resources/workspace/diagnostic/ckc-source-valid-with-generic-property.properties

official examples
- skipping one example which is invalid. Fixed on master upstream
https://github.com/apache/camel-kafka-connector/issues/767
- fixed false positive for "generic" properties which are not part of
the connector model definition
potential improvements: the clone is taking few seconds. it might be
possible to improve that by doing a shallow clone of a specific folder.

FUSETOOLS2-913 - add tests for validation on Camel Kafka Connector

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorPropertiesDiagnosticTest.java
src/test/resources/workspace/diagnostic/ckc-sink-invalid-source-property.properties

FUSETOOLS2-906 - validate match of (sink|source) properties with

---

src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorPropertiesDiagnosticTest.java
src/test/resources/workspace/diagnostic/ckc-with-duplicatedKeyMixingDashedAndCamelCase.properties

mixed up
potential improvements for another iteration:
- indicate line number of the duplicated one (not just the name)
- provide quickfix to delete one or the other
- do it for non Camel Kafka Connector Properties file (if supported by
runtime)

FUSETOOLS2-909 - diagnostic for duplicated keys when dash and camel case

---

src/main/java/com/github/cameltooling/lsp/internal/codeactions/AbstractQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/InvalidEnumQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyKeyInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelSinkOrSourcePropertyKey.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/AbstractQuickFixTest.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/CamelKafkaConnectorUnknownPropertyQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/InvalidEnumQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfixTest.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorPropertiesDiagnosticTest.java
src/test/resources/camel-kafka-connector-catalog/connector-sink-used-for-test.json

it is suggesting only camel cased properties. Suggesting dashed case properties would be nice to be done in another iteration

FUSETOOLS2-914 - quickfix for typo atributes

---

src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorOfficialExamplesDiagnosticTest.java

as it is now fixed upstream with newly integrated version 0.7.0 of Camel
Kafka Connector

FUSETOOLS2-848 - remove filtered example in test

---

src/test/java/com/github/cameltooling/lsp/internal/diagnostic/CamelKafkaConnectorOfficialExamplesDiagnosticTest.java

for example test
there is no branch or tag for Camel Kafka Connector examples currently.
Using tag on personal repo to avoid breaking tests for newer components
that are not part of the embedded catalog version.
set PRIO as it is to fix the master

FUSETOOLS2-951 - use tag on personal repo to match embeddedlib version

---

src/test/java/com/github/cameltooling/lsp/internal/diagnostic/AbstractDiagnosticTest.java

instead for a timeout from the CI, there will be the list o fall tests
that are failing

Update internal timeout to have clearer error message

---

README.md
pom.xml
src/main/java/com/github/cameltooling/lsp/internal/completion/KafkaTopicCompletionProvider.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KafkaTopicCompletionTest.java

first iteration:
- does not support multi-topics (which is possible for consumer
configuration)
- does not support connection that requires authentication
- use localhost:9092 by default
- use system property to override connection url (not convenient for
language server clients but useful for testing)
next iterations:
- connection url provided with a setting https://issues.redhat.com/browse/FUSETOOLS2-1059
- support credentials https://issues.redhat.com/browse/FUSETOOLS2-1060
- support of multi-topics https://issues.redhat.com/browse/FUSETOOLS2-1061
- use `brokers` attribute if provided in Camel URL property https://issues.redhat.com/browse/FUSETOOLS2-1062
- completion for some attributes that can be retrieved from a connected
instance? partitionKey? others? …

FUSETOOLS2-1057 - provide completion for kafka topic

---

pom.xml
src/main/java/com/github/cameltooling/lsp/internal/completion/KameletTemplateIdCompletionProvider.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KameletCompletionTest.java

first iteration:
- ~requires locally built version until version is published on Apache
Snapshots. the version is currently main-SNAPSHOT, this will need to be updated.~ https://repository.apache.org/content/repositories/snapshots/org/apache/camel/kamelets/camel-kamelets-catalog/main-SNAPSHOT/
- no distinction between source and sink
- no description
- Catalog is reloaded on each completion call in a kamelet template Id
part

FUSETOOLS2-1097 - provide completion for kamelet id

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/catalog/util/KameletsCatalogManager.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/AbstractQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/InvalidEnumQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/codeactions/UnknownPropertyQuickfix.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelEndpointCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/CamelPropertiesCompletionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/KameletTemplateIdCompletionProvider.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentAndPathUriInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelComponentURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelUriElementInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamKeyURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamValueURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyEntryInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/propertiesfile/CamelPropertyValueInstance.java
src/main/java/com/github/cameltooling/lsp/internal/modelinemodel/CamelKModelinePropertyOption.java

nota: it requires a lot of changes just to propagate the Catalog. I
think I need to change the way it is provided to various model elements
to avoid that (pass the textDocumentService maybe instead of teh specifc
catalogs?) but work for a distinct PR
no notable changes from use rpoint of view (few milliseconds gain speed) but it allows to have a structure more coherent to other catalogs and open possibility to have a dynamic one

FUSETOOLS2-1107 - provide cached KameletCatalog

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/util/KameletsCatalogManager.java

fixing compilation error on master due to latest snapshots

Follow API Update - no more IOException thrown by KameletsCatalog

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ComponentNameConstants.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/OptionParamKeyURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/PathParamURIInstance.java
src/test/java/com/github/cameltooling/lsp/internal/completion/KameletCompletionTest.java

~one point not clear if some "common" properties needs to be kept or not https://chat.google.com/room/AAAAeFFdN0E/YCC1TvufStA (there were provided before so not changing the behavio rinthis PR. it can still be changed later)~ it is normal to have them

FUSETOOLS2-1106 - provide completion for Kamelet properties

---

src/main/java/com/github/cameltooling/lsp/internal/websocket/WebSocketRunner.java
src/test/java/com/github/cameltooling/lsp/internal/RunnerWebSocketTest.java

- provide more precise assertions
- provide more precise teardown in case previous test was affecting the
other ones, like the shutdown was not finished yet and still occupy some
ports.

FUSETOOLS2-903 - try avoid flakiness

---

USAGE_DATA.md
src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/InitializationTelemetryInfo.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/JVM.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/Memory.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/OS.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/Platform.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/TelemetryEvent.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/TelemetryManager.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/telemetry/TelemetryTest.java

Telemetry is part of the LSP specification: https://microsoft.github.io/language-server-protocol/specifications/specification-current/#telemetry_event
the event is created on the [langauge server side](https://github.com/eclipse/lemminx/tree/master/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/telemetry) and the [client is sending the metric](https://github.com/redhat-developer/vscode-xml/commit/ee25f3abe24015dd11e01a8e9a6dfaa4f3875af1#diff-933541f88e08dbbc0a55ba6ccddf49d2e6a53b0f4f5a71a42a6ec691d1be24a3R41-R43) to Red Hat woopra if telemetry is enabled.
in combination with https://github.com/camel-tooling/camel-lsp-client-vscode/pull/690 , we can have this kind of report: https://app.woopra.com/project/test.vscode/analyze/report/trends/c0afwq5qlb

FUSETOOLS2-1188 - provide metrics

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java

it avoids to have a very long name based on the Client name.
before, name was often cropped and a lot of it doesn't provide a lot of values:
after:

FUSETOOLS2-871 - provide specific label for outline titles

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelCompletionRobustnessTest.java

avoids NPE when the document for which the completion is requested is
not opened, or wasn't opened with same URI 2 times; or was already
closed.
In theory, it should not happened. The client should handle it. But
noticed the NPE in Eclipse LSP4E logs.

FUSETOOLS2-1240 - improve robustness on completion for non-opened document

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java

outline titles"
This reverts commit f0018d9a021c7c9fea51c33fd774416d524eef49.
Eclipse LSP4E is breaking completely with this new feature. Reverting the time that LSP4E is fixing the issue.

FUSETOOLS2-1251 - Revert "FUSETOOLS2-871 - provide specific label for

---

pom.xml

I checked that is no more snapshots version in dependencies
This PR modifies the version to a non-snapshot version
see https://github.com/camel-tooling/camel-language-server/blob/master/Contributing.md#how-to-release

Prepare for 1.2.0 release

---

.circleci/config.yml
.classpath
.github/workflows/maven.yml
.settings/org.eclipse.jdt.core.prefs
pom.xml

Java 11 is now required for the Camel language Server. It does not mean
that it requires Java 11 for your Camel runtime.
- Java 8 is EOL
- It will allow to upgrade Camel Quarkus catalog which requires java 11

FUSETOOLS2-1229 - Drop Java 8 support

---

USAGE_DATA.md
src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelper.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/TelemetryLanguage.java
src/main/java/com/github/cameltooling/lsp/internal/telemetry/TelemetryManager.java
src/test/java/com/github/cameltooling/lsp/internal/telemetry/TelemetryTest.java

heuristic to detect if it s a Camel file or not is not perfect but it
the best that we were using so far.
it will allow to have this kind of report https://app.woopra.com/project/test.vscode/analyze/report/trends/j6rpgiwdyn when used in combination with https://github.com/camel-tooling/camel-lsp-client-vscode/pull/693

FUSETOOLS2-1222 - provide language of Camel files opened

---

src/main/java/com/github/cameltooling/lsp/internal/catalog/util/CamelNodeDetailsUtils.java
src/main/java/com/github/cameltooling/lsp/internal/folding/FoldingRangeProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/folding/FoldingRangeChoiceTest.java
src/test/resources/workspace/LinearRoute.java
src/test/resources/workspace/My3LinearRoutes.java
src/test/resources/workspace/RouteWithChoice.java
src/test/resources/workspace/RouteWithChoiceAndEnd.java
src/test/resources/workspace/RoutesWithChoice.java

- for now only for choice as identified first as an interesting use case
- there is a special treat to handle the .end() case (which is the most
interesting one) because the CamelNodeDetails model provided by Camel
does not surface it

FUSETOOLS2-1232 - provide folding range for choice in java files

---

.circleci/config.yml

circleci/* are deprecated in favor of cimg/*

FUSETOOLS2-1286 - migrate to Circle CI images

---

pom.xml
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/parser/ParserXMLFileHelperTest.java
src/test/java/com/github/cameltooling/lsp/internal/util/TestLogAppender.java
src/test/java/com/github/cameltooling/lsp/internal/util/TestLoggerUtil.java

tricky part was to update the tests. the Appender is a bit trickier to
setup and also requires to set the log level

Upgrade log4j implementation for slf4j from 1.x to 2.16

---

src/main/java/com/github/cameltooling/lsp/internal/diagnostic/ConnectedModeDiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticRunner.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/DiagnosticService.java
src/main/java/com/github/cameltooling/lsp/internal/diagnostic/EndpointDiagnosticService.java
src/test/java/com/github/cameltooling/lsp/internal/diagnostic/ConnectedModeDiagnosticTest.java
src/test/resources/workspace/diagnostic/camel-with-knative-endpoint.java
src/test/resources/workspace/diagnostic/camel-with-knative-endpoint.xml
src/test/resources/workspace/diagnostic/camel-with-kubernetes-endpoint.java
src/test/resources/workspace/diagnostic/camel-with-kubernetes-endpoint.xml

kubernetes and knative
choose to not check if there is a connection active or no for 2 reasons:
- avoids to potentially slow down validation
- still remains a bit interesting to have the hint when there is the connection to encourage users to use completion
limitation: available for XML and Java only
good visibility in Eclipse:
Not good visibility in VS Code (but well that the client choice
)

FUSETOOLS2-1377 - Provide hint for connected mode completion for

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineCompletionprocessor.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineFileType.java
src/main/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineInsertionProcessor.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKModelineInsertionParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKModelineParser.java
src/test/java/com/github/cameltooling/lsp/internal/completion/modeline/CamelKModelineInsertionTest.java

4. Approved PR
4. [x] Green **main** branch build
-----
Adds support to include camelk modeline comment when available.
It works for any
* Java file
* Any XML file ending in `.camelk.xml`
* Any YAML file ending in `camelk.yaml` or `camelk.yml`
Completion is proposed in any empty line that is preceded by blank (spaces, new lines, tabs) or the specific file type comments. 
Completion proposed depends on file-type.
As improvement points in the future, 
* Allow it if the yaml file …

FUSETOOLS2-574 - CamelK Modeline insertion autocompletion

---

README.md
src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/test/java/com/github/cameltooling/lsp/internal/AbstractCamelLanguageServerTest.java
src/test/java/com/github/cameltooling/lsp/internal/CamelCatalogVersionTest.java

Only the classic catalog is covered. It allows to cover the Camel
Quarkus use case. It will cover the SpringBoot based use case when it
will be productized.

FUSETOOLS2-1677 - improve support for productized catalog

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/resources/workspace/crd-like.yaml

Note: The naming of some classes are misleaded, it is no more only for Camel K, reported https://issues.redhat.com/browse/FUSETOOLS2-1816

FUSETOOLS2-1815 - Support CRD Yaml

---

src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/CamelLanguageServerTest.java
src/test/resources/workspace/plain.camel.yaml

it requires the file to be named *.camel.yaml, it follows same pattern than for yaml schema association.

FUSETOOLS2-1817 - Support Plain Camel yaml

---

src/main/java/com/github/cameltooling/lsp/internal/parser/CamelKYamlDSLParser.java

use options as recommended, and given current implementation it will have the exact same behavior
```
/**
* @deprecated use options
*/
@Deprecated
public SafeConstructor() {
this(new LoaderOptions());
}
```

Remove usage of deprecated constructor for Yaml parser

---

src/main/java/com/github/cameltooling/lsp/internal/parser/CamelYamlDSLParser.java
src/main/java/com/github/cameltooling/lsp/internal/parser/ParserFileHelperFactory.java
src/test/java/com/github/cameltooling/lsp/internal/parser/CamelKYamlDSLParserTest.java

supports plain Yaml
for other languages Kotlin, JS and groovy:
- created https://issues.redhat.com/browse/FUSETOOLS2-1825 for JS as it seems simple
- for the 2 others we cannot use the same trick of filename pattern and given that it is not part of languages priorities, I think we can live with it for now

FUSETOOLS2-1816 - rename CamelKYaml related things which can now

---

src/test/java/com/github/cameltooling/lsp/internal/completion/KafkaTopicCompletionTest.java

The goal of the test is to ensure that the end-user receive the completion feedback in less than a second. The timeout on the whole test before was impacted by the time to setup the environment for the test. Keeping a timeout at test level so that in case it hangs, it does not hangs for several minutes.

FUSETOOLS2-1870 - avoid flakiness by checking timeout more precisely

---

.circleci/config.yml
.github/workflows/main.yml

based on https://github.com/camel-tooling/camel-language-server/pull/876
configure Sonar analysis for Main branch
created a specific workflow instead of reusing Matrixes despite
replaying one configuration of test (ubuntu/JDK11) for the following
reasons:
- not the exact same maven parameters as 2 tests must be deactivated due to a bug in Jacoco coverage (or the way we configure it, or the interaction between JUnit and Jacoco)
- it will allow to gather also the sign and deploy in this config and keep it a bit more readable
- Keep it consistent with camel-debug-adapter for which the choice was made this way
Note:
SONAR_TOKEN added, see https://github.com/camel-tooling/camel-language-server/settings/secrets/actions

1911 sonar analysis

---

.github/workflows/jdks.yml

Small update according to the issue verification comment:
https://issues.redhat.com/browse/FUSETOOLS2-1907
Before:
After:

FUSETOOLS2-1907 - Add java version variable

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/PomCompletionProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/completion/PomCompletionTest.java

https://github.com/camel-tooling/camel-language-server/assets/1105127/e4b31b42-6c9c-4b60-a142-1c24cf0ac01f
ideas for other iterations:
- provide completion only inside a profiles block
- provide completion only when it is a Camel Quarkus project
- include profiles block when not available

FUSETOOLS2-2120 - Provide Camel Quarkus debug profile in completion

---

src/main/resources/log4j2.properties

- keep debug only for our code
- use info for others
Since changes in dependencies, the debug logging is now too much verbose to be useful on a day to day basis.

Configure log levels

---

.classpath
.github/workflows/jdks.yml
.github/workflows/main.yml
.github/workflows/os.yml
.settings/org.eclipse.jdt.core.prefs
pom.xml
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelComponentOptionEnumerationValuesTest.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CompleteIdOnDirectEndpointsTest.java

- Java 17 is required
- The `org.apache.camel.ExchangePattern` has removed `InOptionalOut`.
- Direct VM and VM component has been removed
- No Camel Kafka Connector catalog is provided, keep 3.21.0 for it but
not sure how long it would be possible

FUSETOOLS2-2133 - use Camel 4

---

.github/workflows/jdks.yml
.github/workflows/main.yml
pom.xml

artifact
- it will simplify consuming it after compared to having it as an artifact on GitHub Workflow
- CycloneDX Maven plugin is providing it automatically on package/deploy

FUSETOOLS2-2196 - provide sbom with specific classifier as Maven

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionValuesCompletionsFuture.java
src/test/java/com/github/cameltooling/lsp/internal/completion/CamelKubernetesServicesCompletionTest.java

Continue #990 and #995
Now instead of auto-completing the whole value of the parameter, the string can contain several placeholders and other pieces of string that won't get removed by the auto-completion.
[Screencast from 2023-10-13 13-49-40.webm](https://github.com/camel-tooling/camel-language-server/assets/726590/60b33a05-ee2d-4701-8fab-9d2e35ac7a2e)

feature: Auto-completion for kubernetes mid-string

---

src/main/java/com/github/cameltooling/lsp/internal/completion/CamelOptionNamesCompletionsFuture.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/CamelURIInstance.java
src/main/java/com/github/cameltooling/lsp/internal/instancemodel/ComponentNameConstants.java
src/test/java/com/github/cameltooling/lsp/internal/completion/TwitterGeographySearchCompletionTest.java

Adds a snippet if trying to get completion for the twitter-search
component. The required query parameters (latitude, longitude, radius
and distanceMetric) are provided with placeholder values.
Signed-off-by: Marcelo Henrique Diniz de Araujo <mdinizde@redhat.com>

FUSETOOLS2-1419: Provide Twitter geography search snippet completion

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/main/java/com/github/cameltooling/lsp/internal/completion/PomCompletionProcessor.java
src/test/java/com/github/cameltooling/lsp/internal/completion/PomCompletionTest.java

there will be completion provided sometimes not at the exact right-place but should be fine for now.
to have a good ones in this iteration the user will have to use the correct runtime provider otherwise it will end up with not specific to their runtime dependency. To improve in the future by helping to set the runtime provider or to look to the content of the pom.xml

FUSETOOLS2-2478 - completion for dependencies of Camel component in pom

---

src/main/java/com/github/cameltooling/lsp/internal/CamelLanguageServer.java

it avoids having warning messages logged with stacktraces. It helps to clarify log and avoid misleading information.
other Langauge servers  used the same workaround: https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2893/files https://github.com/eclipse/lsp4mp/blob/f191f42ec1a311937ecadb198c7498194be2dac3/microprofile.ls/org.eclipse.lsp4mp.ls/src/main/java/org/eclipse/lsp4mp/ls/MicroProfileLanguageServer.java#L187
it will avoid this kind of message in the output:
```
Nov 19, 2024 12:10:14 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleNotification
WARNING: Notification threw an exception: {
“jsonrpc”: “2.0",
“method”: “$/setTrace”,
“params”: {
“value”: “off”
}
}
java.lang.UnsupportedOperationException
at org.eclipse.lsp4j.services.LanguageServer.setTrace(LanguageServer.java:125)
at …
```

Provide empty implementation for setTrace

---

src/main/resources/log4j2.properties

otherwise when trying to walk files to delete old logs, depending on the content of /tmp and the rights, an exception can be thrown
It will also have the side effect to be more performant by not scanning the full /tmp folder everyday or every time the log reach 10MB

FUSETOOLS2-2508 - Configure log to use a specific Camel LSP folder

---

src/main/java/com/github/cameltooling/lsp/internal/CamelTextDocumentService.java
src/test/java/com/github/cameltooling/lsp/internal/folding/FoldingRangeRouteTest.java

it sounds like the IDE is requesting a folding range (so places to place little +/- to fold a part of the text) on a not opened document. I do not understand what could be the purpose. Ignoring the request to avoid NPE until we have more information for another use case (uri provided in a different shape?). It will avoid the NPE and the missing functionalities won't be critical.

FUSETOOLS2-2529 - avoid NPE in FoldingRange

---

pom.xml

due to https://github.com/CycloneDX/cyclonedx-maven-plugin/issues/597
locally got the sbom built:
```
[INFO] CycloneDX: Creating BOM version 1.6 with 132 component(s)
[INFO] CycloneDX: Writing and validating BOM (XML): /home/apupier/git/camel-language-server/target/bom.xml
[INFO]            attaching as camel-lsp-server-1.32.0-SNAPSHOT-cyclonedx.xml
[INFO] CycloneDX: Writing and validating BOM (JSON): /home/apupier/git/camel-language-server/target/bom.json
[WARNING] Unknown keyword meta:enum - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
[WARNING] Unknown keyword deprecated - you should define your own Meta Schema. If the keyword is irrelevant for validation, just …
```

FUSETOOLS2-2584 - workaround to publish SBom

---

src/test/java/com/github/cameltooling/lsp/internal/RunnerWebSocketTest.java

On the GitHub CI, recently on Mac, the hostname is very often not resolved and return null, we need this information to start the test. Also, this websocket feature is not very used a lot.

Disabling 2 very flaky tests on Mac related to Websocket
